#!/bin/bash

# Designed to be run by systemd timer every 30 seconds and alerts if battery is low
BATTERY_LEVEL=$(omarchy-battery-remaining)
BATTERY_STATE=$(upower -i $(upower -e | grep 'BAT') | grep -E "state" | awk '{print $2}')

#Alerta carga superior (>=80%)
BATTERY_THRESHOLD_F=80
NOTIFICATION_FLAG_F="/run/user/$UID/omarchy_battery_notified_80"

send_notification_F() {
  notify-send -u critical "󱐋 Ready to disconect!" "Battery is up to ${1}%" -i battery-caution -t 30000
  omarchy-hook battery-low "$1"
}

if [[ -n $BATTERY_LEVEL && $BATTERY_LEVEL =~ ^[0-9]+$ ]]; then
  if [[ $BATTERY_STATE == "charging" ]] && (( BATTERY_LEVEL >= BATTERY_THRESHOLD_F )); then
    if [[ ! -f $NOTIFICATION_FLAG_F ]]; then
      send_notification_F $BATTERY_LEVEL
      touch $NOTIFICATION_FLAG_F
    fi
  else
    rm -f $NOTIFICATION_FLAG_F
  fi
fi
#Alerta carga sugerida (<30%)
BATTERY_THRESHOLD_S=30
NOTIFICATION_FLAG_S="/run/user/$UID/omarchy_battery_notified_30"

send_notification_S() {
  notify-send -u critical "󱐋 Recharge if psossible!" "Battery is down to ${1}%" -i battery-caution -t 30000
  omarchy-hook battery-low "$1"
}

if [[ -n $BATTERY_LEVEL && $BATTERY_LEVEL =~ ^[0-9]+$ ]]; then
  if [[ $BATTERY_STATE == "discharging" ]] && (( BATTERY_LEVEL <= BATTERY_THRESHOLD_S )); then
    if [[ ! -f $NOTIFICATION_FLAG_S ]]; then
      send_notification_S $BATTERY_LEVEL
      touch $NOTIFICATION_FLAG_S
    fi
  else
    rm -f $NOTIFICATION_FLAG_S
  fi
fi

#Alerta carga inmmediata (<10%)
BATTERY_THRESHOLD=10
NOTIFICATION_FLAG="/run/user/$UID/omarchy_battery_notified_10"
send_notification() {
  notify-send -u critical "󱐋 Time to recharge!" "Battery is down to ${1}%" -i battery-caution -t 30000
  omarchy-hook battery-low "$1"
}

if [[ -n $BATTERY_LEVEL && $BATTERY_LEVEL =~ ^[0-9]+$ ]]; then
  if [[ $BATTERY_STATE == "discharging" ]] && (( BATTERY_LEVEL <= BATTERY_THRESHOLD )); then
    if [[ ! -f $NOTIFICATION_FLAG ]]; then
      send_notification $BATTERY_LEVEL
      touch $NOTIFICATION_FLAG
    fi
  else
    rm -f $NOTIFICATION_FLAG
  fi
fi
